table 'DIM - SUPERVISOR'
	lineageTag: 7e270ce1-8c76-4820-9a8f-1087d95d6c52

	column SUP_CODE
		dataType: string
		lineageTag: 30d61791-ddbd-4bfd-b5c3-eef878631fd2
		summarizeBy: none
		sourceColumn: SUP_CODE

		annotation SummarizationSetBy = Automatic

	column SUP_NAME
		dataType: string
		lineageTag: 3c847fb4-b89d-4131-b654-3cd3fffc1163
		summarizeBy: none
		sourceColumn: SUP_NAME

		annotation SummarizationSetBy = Automatic

	partition 'DIM - SUPERVISOR' = m
		mode: import
		source =
				let
				    Source = Sql.Databases("sg-sea-prod-syn-01.sql.azuresynapse.net"),
				    pvcfcprodsqlpool = Source{[Name="pvcfcprodsqlpool"]}[Data],
				    sil_DIM_SUPERVISOR = pvcfcprodsqlpool{[Schema="sil",Item="DIM_SUPERVISOR"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(sil_DIM_SUPERVISOR,{"W_INSERT_DT", "W_BATCH_ID"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

