table 'DIM - ORDER TYPE'
	lineageTag: dd691ac0-e2e8-45e0-8f07-416789fd2316

	column ORDER_TYPE
		dataType: string
		lineageTag: ee910e9e-0565-4152-b531-e0be37672367
		summarizeBy: none
		sourceColumn: ORDER_TYPE

		annotation SummarizationSetBy = Automatic

	column ORDER_TYPE_DESC
		dataType: string
		lineageTag: dd8d36a2-b2c9-46a3-9b52-7370d1c97252
		summarizeBy: none
		sourceColumn: ORDER_TYPE_DESC

		annotation SummarizationSetBy = Automatic

	partition 'DIM - ORDER TYPE' = m
		mode: import
		source =
				let
				    Source = Sql.Databases("sg-sea-prod-syn-01.sql.azuresynapse.net"),
				    pvcfcprodsqlpool = Source{[Name="pvcfcprodsqlpool"]}[Data],
				    sil_DIM_ORDER_TYPE = pvcfcprodsqlpool{[Schema="sil",Item="DIM_ORDER_TYPE"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(sil_DIM_ORDER_TYPE,{"W_INSERT_DT", "W_BATCH_ID"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

