table 'DIM - EQUI TYPE'
	lineageTag: 3b5d2d52-978a-4882-b5a1-d4607d99e92b

	column EQUI_TYPE_CODE
		dataType: string
		lineageTag: 56938364-5101-4c17-841b-f8c662b7e05a
		summarizeBy: none
		sourceColumn: EQUI_TYPE_CODE

		annotation SummarizationSetBy = Automatic

	column EQUI_TYPE_DESC
		dataType: string
		lineageTag: d16a498c-97f2-453c-baeb-e4479305bb1a
		summarizeBy: none
		sourceColumn: EQUI_TYPE_DESC

		annotation SummarizationSetBy = Automatic

	partition 'DIM - EQUI TYPE' = m
		mode: import
		source =
				let
				    Source = Sql.Databases("sg-sea-prod-syn-01.sql.azuresynapse.net"),
				    pvcfcprodsqlpool = Source{[Name="pvcfcprodsqlpool"]}[Data],
				    sil_DIM_EQUI_TYPE = pvcfcprodsqlpool{[Schema="sil",Item="DIM_EQUI_TYPE"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(sil_DIM_EQUI_TYPE,{"W_INSERT_DT", "W_BATCH_ID"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

