table 'DIM - REPORTING LINE BS'
	lineageTag: 1350fcd3-eb4d-4997-bfe4-f8f8f51cf266

	measure 'Is Highlight Color BS' = SELECTEDVALUE('DIM - REPORTING LINE BS'[BOLD])
		lineageTag: 71f62a0b-f11a-48a9-a21e-54123dfb1093

	column ITEM_NO
		dataType: string
		isKey
		lineageTag: a960e4c8-cc88-4072-a802-11601bc77f63
		summarizeBy: none
		sourceColumn: ITEM_NO

		annotation SummarizationSetBy = Automatic

	column DESC_VN
		dataType: string
		lineageTag: 5df7f28d-93e3-42f9-b576-fdc2e770c8f7
		summarizeBy: none
		sourceColumn: DESC_VN

		annotation SummarizationSetBy = Automatic

	column DESC_EN
		dataType: string
		lineageTag: 9007ae2f-a821-4a13-a32f-c579f41816bc
		summarizeBy: none
		sourceColumn: DESC_EN

		annotation SummarizationSetBy = Automatic

	column NOTE
		dataType: string
		lineageTag: d5c71e27-e314-4aa2-a453-f64930face51
		summarizeBy: none
		sourceColumn: NOTE

		annotation SummarizationSetBy = Automatic

	column BOLD
		dataType: string
		lineageTag: e4cd4b60-bf3f-42a8-bd9e-6bc8c312aafb
		summarizeBy: none
		sourceColumn: BOLD

		annotation SummarizationSetBy = Automatic

	column ITALIC
		dataType: string
		lineageTag: 6e501a34-1b3c-4562-83ba-cbf69480b2ac
		summarizeBy: none
		sourceColumn: ITALIC

		annotation SummarizationSetBy = Automatic

	column 'SIGN (Hide)'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2caf1b73-2d99-497a-98cf-daa0b7ff1246
		summarizeBy: sum
		sourceColumn: SIGN (Hide)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SIGN = ```
			SWITCH( TRUE(),
			        LEFT('DIM - REPORTING LINE BS'[ITEM_NO],1) IN {"1", "2"}, 1, 
			        LEFT('DIM - REPORTING LINE BS'[ITEM_NO],1) IN {"3", "4"}, -1, 
			        1)
			```
		dataType: int64
		formatString: 0
		lineageTag: c69caf4e-1b2c-44d9-b325-df23c6d424c5
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	partition 'DIM - REPORTING LINE BS' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("vVrdb9vWFf9XLvyUrnZgUbKTPPTBdhxHgCenluxmKPpAU5R4F+qS4Ydt9anFHvIQ", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ITEM_NO = _t, DESC_VN = _t, DESC_EN = _t, NOTE = _t, BOLD = _t, ITALIC = _t, SIGN = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"SIGN", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"SIGN", "SIGN (Hide)"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

