table 'DIM - MAINT ACT TYPE'
	lineageTag: 5de4d6e8-6b6b-4ba1-b7cb-84401d0505b7

	column ACT_TYPE_CODE
		dataType: string
		lineageTag: 7b22ecaf-71db-4c36-97b9-10f314d6a75a
		summarizeBy: none
		sourceColumn: ACT_TYPE_CODE

		annotation SummarizationSetBy = Automatic

	column ACT_TYPE_DESC
		dataType: string
		lineageTag: 0d6c04cc-842f-4d3e-b1e2-fb2fe8f0b092
		summarizeBy: none
		sourceColumn: ACT_TYPE_DESC

		annotation SummarizationSetBy = Automatic

	partition 'DIM - MAINT ACT TYPE' = m
		mode: import
		source =
				let
				    Source = Sql.Databases("sg-sea-prod-syn-01.sql.azuresynapse.net"),
				    pvcfcprodsqlpool = Source{[Name="pvcfcprodsqlpool"]}[Data],
				    sil_DIM_MAINT_ACT_TYPE = pvcfcprodsqlpool{[Schema="sil",Item="DIM_MAINT_ACT_TYPE"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(sil_DIM_MAINT_ACT_TYPE,{"W_INSERT_DT", "W_BATCH_ID"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

