table 'DIM - HISTORY DATA TYPE'
	lineageTag: ed4b0110-8601-4618-906f-29802ce3580f

	column DATA_TYPE
		dataType: string
		lineageTag: ede19d47-cbab-4358-b4c4-6230e1c7f37b
		summarizeBy: none
		sourceColumn: DATA_TYPE

		annotation SummarizationSetBy = Automatic

	column DATA_TYPE_DESC
		dataType: string
		lineageTag: 3465101f-cfda-4deb-b568-ee0118caaf44
		summarizeBy: none
		sourceColumn: DATA_TYPE_DESC

		annotation SummarizationSetBy = Automatic

	partition 'DIM - HISTORY DATA TYPE' = m
		mode: import
		source =
				let
				    Source = Sql.Databases("sg-sea-prod-syn-01.sql.azuresynapse.net"),
				    pvcfcprodsqlpool = Source{[Name="pvcfcprodsqlpool"]}[Data],
				    sil_DIM_HISTORY_DATA_TYPE = pvcfcprodsqlpool{[Schema="sil",Item="DIM_HISTORY_DATA_TYPE"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(sil_DIM_HISTORY_DATA_TYPE,{"W_INSERT_DT", "W_BATCH_ID"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

