table 'DIM - USER STATUS EXCHANGE'
	lineageTag: ac879732-88ad-4ac1-bdd6-0361f868945f

	column USER_STATUS_EXCHANGE
		dataType: string
		lineageTag: cdd38f91-a731-4338-bf67-0d196862a151
		summarizeBy: none
		sourceColumn: USER_STATUS_EXCHANGE

		annotation SummarizationSetBy = Automatic

	column USER_STATUS_EXCHANGE_DESC
		dataType: string
		lineageTag: 70f92222-f366-4278-a5c3-00e902aac153
		summarizeBy: none
		sourceColumn: USER_STATUS_EXCHANGE_DESC

		annotation SummarizationSetBy = Automatic

	partition 'DIM - USER STATUS EXCHANGE' = m
		mode: import
		source =
				let
				    Source = Sql.Databases("sg-sea-prod-syn-01.sql.azuresynapse.net"),
				    pvcfcprodsqlpool = Source{[Name="pvcfcprodsqlpool"]}[Data],
				    sil_DIM_USER_STATUS_EXCHANGE = pvcfcprodsqlpool{[Schema="sil",Item="DIM_USER_STATUS_EXCHANGE"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(sil_DIM_USER_STATUS_EXCHANGE,{"W_INSERT_DT", "W_BATCH_ID"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

