table 'FACT - SCHEDULING OVERVIEW LIST'
	lineageTag: d3424b48-adb5-44e6-b16e-dce72356865a

	column ORDER_TYPE
		dataType: string
		lineageTag: 2d67eb03-bfbe-477a-81ff-61a9746d9128
		summarizeBy: none
		sourceColumn: ORDER_TYPE

		annotation SummarizationSetBy = Automatic

	column MAINT_ITEM
		dataType: string
		lineageTag: 06224131-7545-4e70-9b75-7c30d21a935a
		summarizeBy: none
		sourceColumn: MAINT_ITEM

		annotation SummarizationSetBy = Automatic

	column MAINT_PLAN
		dataType: string
		lineageTag: 8a5c750a-bc3c-4301-a62f-f18dc2606f4d
		summarizeBy: none
		sourceColumn: MAINT_PLAN

		annotation SummarizationSetBy = Automatic

	column CALL_NUMBER
		dataType: int64
		formatString: 0
		lineageTag: 2ca14613-6f9e-48fa-b5d6-55345430bcc9
		summarizeBy: sum
		sourceColumn: CALL_NUMBER

		annotation SummarizationSetBy = Automatic

	column CALL_OBJ_PLAN_DATE
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 3d9cafdf-1ad6-49e7-bd14-e3b3ec0dd555
		summarizeBy: none
		sourceColumn: CALL_OBJ_PLAN_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column MAINT_CALL_PLAN_DATE
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: eb485d5a-4887-4c75-bfc7-a43901ffb2d8
		summarizeBy: none
		sourceColumn: MAINT_CALL_PLAN_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column SCHE_START_DATE
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 899d155a-9d77-4b1a-82c6-1e7be4ffed7d
		summarizeBy: none
		sourceColumn: SCHE_START_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column ORDER_NUMBER
		dataType: string
		lineageTag: 3da92fa4-b9dc-4f04-b15d-3b9051eb0aa1
		summarizeBy: none
		sourceColumn: ORDER_NUMBER

		annotation SummarizationSetBy = Automatic

	column WORK_CENTER
		dataType: string
		lineageTag: 7d834a49-dbd6-41e0-ae06-3c837bd00ccc
		summarizeBy: none
		sourceColumn: WORK_CENTER

		annotation SummarizationSetBy = Automatic

	column WBS_ELEMENT
		dataType: string
		lineageTag: 00974fc5-e3f2-4e39-9b4b-ced300060eeb
		summarizeBy: none
		sourceColumn: WBS_ELEMENT

		annotation SummarizationSetBy = Automatic

	column ASSET_SUBNUMBER
		dataType: string
		lineageTag: 822e2b38-d084-46b0-bdc7-748048be7d39
		summarizeBy: none
		sourceColumn: ASSET_SUBNUMBER

		annotation SummarizationSetBy = Automatic

	column STAND_ORDER_NUMBER
		dataType: string
		lineageTag: a333995b-bc77-431a-875f-6842798d7224
		summarizeBy: none
		sourceColumn: STAND_ORDER_NUMBER

		annotation SummarizationSetBy = Automatic

	column TAG_NAME
		dataType: string
		lineageTag: acb514ee-bf31-44d6-be87-b5b5e20d56b7
		summarizeBy: none
		sourceColumn: TAG_NAME

		annotation SummarizationSetBy = Automatic

	column SETTLE_IND
		dataType: string
		lineageTag: 250faa56-0918-468e-a4b4-a727b0328993
		summarizeBy: none
		sourceColumn: SETTLE_IND

		annotation SummarizationSetBy = Automatic

	column SERIAL_NUMBER
		dataType: string
		lineageTag: 074ac48a-e1b0-4538-9506-8e6295b6bfa2
		summarizeBy: none
		sourceColumn: SERIAL_NUMBER

		annotation SummarizationSetBy = Automatic

	column SCHED_STATUS_CALL
		dataType: string
		lineageTag: 9b9a2674-b4a3-4a35-b66e-c942c9470a6e
		summarizeBy: none
		sourceColumn: SCHED_STATUS_CALL

		annotation SummarizationSetBy = Automatic

	column SCHED_STATUS
		dataType: string
		lineageTag: a1a217b0-5ef6-4fcd-8021-f2cfcbc42918
		summarizeBy: none
		sourceColumn: SCHED_STATUS

		annotation SummarizationSetBy = Automatic

	column SALES_ORGANI
		dataType: string
		lineageTag: 0c350975-f66f-434f-8ffd-3f97242bf341
		summarizeBy: none
		sourceColumn: SALES_ORGANI

		annotation SummarizationSetBy = Automatic

	column SALES_DOC_ITEM
		dataType: string
		lineageTag: 03807c9b-8af0-4012-afca-6dadf4869f44
		summarizeBy: none
		sourceColumn: SALES_DOC_ITEM

		annotation SummarizationSetBy = Automatic

	column SALES_DOC
		dataType: string
		lineageTag: fee12b9f-13ce-426c-9a58-d65ce2b5e589
		summarizeBy: none
		sourceColumn: SALES_DOC

		annotation SummarizationSetBy = Automatic

	column ROOM
		dataType: string
		lineageTag: e5dd0ef2-fa26-4fbf-876d-b041d948427f
		summarizeBy: none
		sourceColumn: ROOM

		annotation SummarizationSetBy = Automatic

	column PUR_ORDER_ITEM
		dataType: string
		lineageTag: 489dad5b-5dd2-4891-b088-2730a1b03708
		summarizeBy: none
		sourceColumn: PUR_ORDER_ITEM

		annotation SummarizationSetBy = Automatic

	column PUR_ORDER_NUMBER
		dataType: string
		lineageTag: fa00a47a-d1fa-4d70-8491-f01949ad328d
		summarizeBy: none
		sourceColumn: PUR_ORDER_NUMBER

		annotation SummarizationSetBy = Automatic

	column WORK_CENTER_ID
		dataType: string
		lineageTag: 535887af-a3f9-4910-be27-51e76303fd41
		summarizeBy: none
		sourceColumn: WORK_CENTER_ID

		annotation SummarizationSetBy = Automatic

	column SAMPLE_NUMBER
		dataType: string
		lineageTag: 65d80cfd-e5c5-496a-9033-8cfa04fe64cd
		summarizeBy: none
		sourceColumn: SAMPLE_NUMBER

		annotation SummarizationSetBy = Automatic

	column LIST_NUMBER
		dataType: int64
		formatString: 0
		lineageTag: b48f2d4f-6f9a-4963-bd4a-22a7a96e7496
		summarizeBy: sum
		sourceColumn: LIST_NUMBER

		annotation SummarizationSetBy = Automatic

	column NOTIF_TYPE
		dataType: string
		lineageTag: 06a7ce3b-a57c-4dd2-8a84-8845cbb1d769
		summarizeBy: none
		sourceColumn: NOTIF_TYPE

		annotation SummarizationSetBy = Automatic

	column NOTIF_NUM
		dataType: string
		lineageTag: a8f75d5e-38f5-4cdc-8a53-67a6292b1d5a
		summarizeBy: none
		sourceColumn: NOTIF_NUM

		annotation SummarizationSetBy = Automatic

	column MATERIAL_NUMBER
		dataType: string
		lineageTag: 0949cbc3-de7e-4adc-9f2e-c7e9150c1474
		summarizeBy: none
		sourceColumn: MATERIAL_NUMBER

		annotation SummarizationSetBy = Automatic

	column MAINT_PLANT
		dataType: string
		lineageTag: c496bd0d-6a4a-4403-b51b-b54e0884c324
		summarizeBy: none
		sourceColumn: MAINT_PLANT

		annotation SummarizationSetBy = Automatic

	column LONG_TEXT
		dataType: string
		lineageTag: c6440816-b5b9-4e33-b3f9-03807fb3cff3
		summarizeBy: none
		sourceColumn: LONG_TEXT

		annotation SummarizationSetBy = Automatic

	column LOC
		dataType: string
		lineageTag: 3adee4fc-27ec-4f3f-80e0-b2795be347cc
		summarizeBy: none
		sourceColumn: LOC

		annotation SummarizationSetBy = Automatic

	column LOC_ACCT_ASSIGN
		dataType: string
		lineageTag: db39b57b-508d-4da5-b778-17ac827b8592
		summarizeBy: none
		sourceColumn: LOC_ACCT_ASSIGN

		annotation SummarizationSetBy = Automatic

	column LAST_ORDER
		dataType: string
		lineageTag: 84b101f0-26dd-4dbd-8e4f-af5c7365c8b3
		summarizeBy: none
		sourceColumn: LAST_ORDER

		annotation SummarizationSetBy = Automatic

	column DIVISION
		dataType: string
		lineageTag: 87823fb4-90b9-4137-84ca-19a68e07390f
		summarizeBy: none
		sourceColumn: DIVISION

		annotation SummarizationSetBy = Automatic

	column INSPECT_LOT_NUMBER
		dataType: string
		lineageTag: 1f7c838f-2cfc-4716-874b-6a83ce717c4c
		summarizeBy: none
		sourceColumn: INSPECT_LOT_NUMBER

		annotation SummarizationSetBy = Automatic

	column FUNCT_LOC_CODE
		dataType: string
		lineageTag: 95132660-74bf-46cb-8d38-bc7c51678f4b
		summarizeBy: none
		sourceColumn: FUNCT_LOC_CODE

		annotation SummarizationSetBy = Automatic

	column ENTRY_NUMBER
		dataType: string
		lineageTag: aa1529e4-f35f-49b6-a030-0691ddec3e5f
		summarizeBy: none
		sourceColumn: ENTRY_NUMBER

		annotation SummarizationSetBy = Automatic

	column DISTRIBUTION_CHANNEL
		dataType: string
		lineageTag: b46e1e13-5f3f-4bf8-b94f-473bb75048e1
		summarizeBy: none
		sourceColumn: DISTRIBUTION_CHANNEL

		annotation SummarizationSetBy = Automatic

	column COST_CENTER
		dataType: string
		lineageTag: d74daa05-692d-49e3-94fb-b158730ff754
		summarizeBy: none
		sourceColumn: COST_CENTER

		annotation SummarizationSetBy = Automatic

	column CONTROL_AREA
		dataType: string
		lineageTag: 5efbcb2e-66e7-4f61-a6ad-efd4ca7bc14d
		summarizeBy: none
		sourceColumn: CONTROL_AREA

		annotation SummarizationSetBy = Automatic

	column COMPLETE_DATE
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: e24acdb3-43d9-44bd-9474-46489acaaee5
		summarizeBy: none
		sourceColumn: COMPLETE_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column COMPANY_CODE
		dataType: string
		lineageTag: 1d4a050f-e8d2-4c89-bad2-e724fba4c3ee
		summarizeBy: none
		sourceColumn: COMPANY_CODE

		annotation SummarizationSetBy = Automatic

	column ASSET_NUMBER
		dataType: string
		lineageTag: d9dd7ba5-03e7-45a7-83ad-bc0ef2963905
		summarizeBy: none
		sourceColumn: ASSET_NUMBER

		annotation SummarizationSetBy = Automatic

	column ABC_IND
		dataType: string
		lineageTag: d2bfd0bc-45ca-49c3-a478-9f950f3fc11e
		summarizeBy: none
		sourceColumn: ABC_IND

		annotation SummarizationSetBy = Automatic

	column MP_BASIC_START_DATE
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 41ea0fc5-aef7-4588-822d-4a5ced5d550b
		summarizeBy: none
		sourceColumn: MP_BASIC_START_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column WO_BASIC_START_DATE
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 5fca058d-fd69-4ab0-93d2-fadf9b8bc9bb
		summarizeBy: none
		sourceColumn: WO_BASIC_START_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column OPER_ACT_NUM
		dataType: string
		lineageTag: b192d277-37b3-4f85-870f-1cf1b0268c1b
		summarizeBy: none
		sourceColumn: OPER_ACT_NUM

		annotation SummarizationSetBy = Automatic

	column MAINT_STRA
		dataType: string
		lineageTag: b82ea31e-9815-4f64-ac90-b75e9be84967
		summarizeBy: none
		sourceColumn: MAINT_STRA

		annotation SummarizationSetBy = Automatic

	column MAIN_PACK_NUM
		dataType: string
		lineageTag: c2a68972-288f-4828-9c01-c359efd05c8e
		summarizeBy: none
		sourceColumn: MAIN_PACK_NUM

		annotation SummarizationSetBy = Automatic

	column EQUI_DESC
		dataType: string
		lineageTag: caa25c45-4dc5-499d-90e7-78b89569f2a4
		summarizeBy: none
		sourceColumn: EQUI_DESC

		annotation SummarizationSetBy = Automatic

	column EQUI_TYPE_CODE
		dataType: string
		lineageTag: 463da488-565e-451b-83a4-efad91e17350
		summarizeBy: none
		sourceColumn: EQUI_TYPE_CODE

		annotation SummarizationSetBy = Automatic

	column ACT_TYPE_CODE
		dataType: string
		lineageTag: d0bf09b9-e40c-40c9-a69b-913049741ee1
		summarizeBy: none
		sourceColumn: ACT_TYPE_CODE

		annotation SummarizationSetBy = Automatic

	column OPER_SHORT_DESC
		dataType: string
		lineageTag: e0c59068-c3c6-4603-91f5-db655ff96ebd
		summarizeBy: none
		sourceColumn: OPER_SHORT_DESC

		annotation SummarizationSetBy = Automatic

	column PLNT_SECT_CODE
		dataType: string
		lineageTag: 057467d9-d230-4b64-b392-948a6a730fd7
		summarizeBy: none
		sourceColumn: PLNT_SECT_CODE

		annotation SummarizationSetBy = Automatic

	column PLANNER_GRP
		dataType: string
		lineageTag: 36b7da44-4afb-47b6-8f51-f2aeb6c64643
		summarizeBy: none
		sourceColumn: PLANNER_GRP

		annotation SummarizationSetBy = Automatic

	column SUP_CODE
		dataType: string
		lineageTag: 68c1b892-83de-47a8-9fcf-4caf1928f3e3
		summarizeBy: none
		sourceColumn: SUP_CODE

		annotation SummarizationSetBy = Automatic

	column GRP_COUNTER
		dataType: string
		lineageTag: d1783f4e-f4d3-4f45-bed2-22716f4bb554
		summarizeBy: none
		sourceColumn: GRP_COUNTER

		annotation SummarizationSetBy = Automatic

	column FREQUENCY
		dataType: string
		lineageTag: 08b1ea6d-e059-4147-b1b1-5bf33de25823
		summarizeBy: none
		sourceColumn: FREQUENCY

		annotation SummarizationSetBy = Automatic

	column SYST_COND
		dataType: string
		lineageTag: 781c5601-b107-4b1f-9307-3ccb8d025a1b
		summarizeBy: none
		sourceColumn: SYST_COND

		annotation SummarizationSetBy = Automatic

	column EQUI_NUMBER
		dataType: string
		lineageTag: 3d99ee55-2929-46d8-9429-59ecb4dc3576
		summarizeBy: none
		sourceColumn: EQUI_NUMBER

		annotation SummarizationSetBy = Automatic

	column MAINT_PLAN_STATUS
		dataType: string
		lineageTag: 6d71ba7e-cbb0-4966-8405-1c869d98fa9a
		summarizeBy: none
		sourceColumn: MAINT_PLAN_STATUS

		annotation SummarizationSetBy = Automatic

	column SYSTEM_STATUS_EXCHANGE
		dataType: string
		lineageTag: bf9993a1-7ec9-414f-bfae-2dfa8e76ca46
		summarizeBy: none
		sourceColumn: SYSTEM_STATUS_EXCHANGE

		annotation SummarizationSetBy = Automatic

	partition 'FACT - SCHEDULING OVERVIEW LIST' = m
		mode: import
		source =
				let
				    Source = Sql.Databases("sg-sea-prod-syn-01.sql.azuresynapse.net"),
				    pvcfcprodsqlpool = Source{[Name="pvcfcprodsqlpool"]}[Data],
				    gld_FACT_SCHEDULING_OVERVIEW_LIST = pvcfcprodsqlpool{[Schema="gld",Item="FACT_SCHEDULING_OVERVIEW_LIST"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(gld_FACT_SCHEDULING_OVERVIEW_LIST,{"W_INSERT_DT"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns","00000000","99991231",Replacer.ReplaceText,{"SCHE_START_DATE"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value",null,"99991231",Replacer.ReplaceValue,{"SCHE_START_DATE"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value3","00000000"," ",Replacer.ReplaceText,{"COMPLETE_DATE"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","00000000"," ",Replacer.ReplaceText,{"MP_BASIC_START_DATE"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value2",{{"SCHE_START_DATE", type date}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed Type1",{{"CALL_OBJ_PLAN_DATE", type date}, {"MAINT_CALL_PLAN_DATE", type date}, {"COMPLETE_DATE", type date}, {"MP_BASIC_START_DATE", type date}, {"WO_BASIC_START_DATE", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

