table 'PARAMETER - ZCO14 MEASURE GROUP'
	lineageTag: 4ec78251-b67f-47e1-a0c4-8b1cd99bbb6d

	measure 'ZCO14 Measures (CPDV)' =
			SWITCH(
			    SELECTEDVALUE('PARAMETER - ZCO14 MEASURE GROUP'[STT],""),
			    1, [Chi phí kế hoạch (ZCO14)],
			    2, CALCULATE([Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 1)),
			    3, CALCULATE([Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 2)),
			    4, CALCULATE([Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 3)),
			    5, CALCULATE([Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 4)),
			    6, CALCULATE([Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 5)),
			    7, CALCULATE([Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 6)),
			    8, CALCULATE([Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 7)),
			    9, CALCULATE([Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 8)),
			    10, CALCULATE([Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 9)),
			    11, CALCULATE([Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 10)),
			    12, CALCULATE([Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 11)),
			    13, CALCULATE([Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 12)),
			    14, [Chi phí lũy kế của đơn vị (ZCO14)],
			    15,
			        IF(
			            ISBLANK(DIVIDE([Chi phí lũy kế của đơn vị (ZCO14)], [Chi phí kế hoạch (ZCO14)])),
			            BLANK(),
			            FORMAT(DIVIDE([Chi phí lũy kế của đơn vị (ZCO14)], [Chi phí kế hoạch (ZCO14)]), "#,0%")
			        )
			    --16, [Chi phí kế hoạch (ZCO14)] - ABS([Chi phí của đơn vị (ZCO14)])
			)
		lineageTag: a05eecd3-3005-4b2a-811e-2262748099e3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ZCO14 Measures (DMQL)' =
			SWITCH(
			    SELECTEDVALUE('PARAMETER - ZCO14 MEASURE GROUP'[STT],""),
			    1, [Chi phí kế hoạch (ZCO14 - DMQL)],
			    2, CALCULATE(-1* [Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 1), 'FACT - CO PHONG BAN'[OBJECT_NO] = "KSPVCA1Z99"),
			    3, CALCULATE(-1 * [Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 2), 'FACT - CO PHONG BAN'[OBJECT_NO] = "KSPVCA1Z99"),
			    4, CALCULATE(-1 * [Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 3), 'FACT - CO PHONG BAN'[OBJECT_NO] = "KSPVCA1Z99"),
			    5, CALCULATE(-1 * [Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 4), 'FACT - CO PHONG BAN'[OBJECT_NO] = "KSPVCA1Z99"),
			    6, CALCULATE(-1 * [Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 5), 'FACT - CO PHONG BAN'[OBJECT_NO] = "KSPVCA1Z99"),
			    7, CALCULATE(-1 * [Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 6), 'FACT - CO PHONG BAN'[OBJECT_NO] = "KSPVCA1Z99"),
			    8, CALCULATE(-1 * [Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 7), 'FACT - CO PHONG BAN'[OBJECT_NO] = "KSPVCA1Z99"),
			    9, CALCULATE(-1 * [Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 8), 'FACT - CO PHONG BAN'[OBJECT_NO] = "KSPVCA1Z99"),
			    10, CALCULATE(-1 * [Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 9), 'FACT - CO PHONG BAN'[OBJECT_NO] = "KSPVCA1Z99"),
			    11, CALCULATE(-1 * [Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 10), 'FACT - CO PHONG BAN'[OBJECT_NO] = "KSPVCA1Z99"),
			    12, CALCULATE(-1 * [Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 11), 'FACT - CO PHONG BAN'[OBJECT_NO] = "KSPVCA1Z99"),
			    13, CALCULATE(-1 * [Chi phí của đơn vị (ZCO14)],FILTER('DIM - DATE',[Month] = 12), 'FACT - CO PHONG BAN'[OBJECT_NO] = "KSPVCA1Z99"),
			    14, CALCULATE(-1 * [Chi phí của đơn vị (ZCO14)], 'FACT - CO PHONG BAN'[OBJECT_NO] = "KSPVCA1Z99"),
			    15,
			        IF(
			            ISBLANK(DIVIDE(CALCULATE(-1 * [Chi phí của đơn vị (ZCO14)], 'FACT - CO PHONG BAN'[OBJECT_NO] = "KSPVCA1Z99"), [Chi phí kế hoạch (ZCO14 - DMQL)])),
			            BLANK(),
			            FORMAT(DIVIDE(CALCULATE(-1 * [Chi phí của đơn vị (ZCO14)], 'FACT - CO PHONG BAN'[OBJECT_NO] = "KSPVCA1Z99"), [Chi phí kế hoạch (ZCO14 - DMQL)]), "#,0%")
			        ),
			    16, [Chi phí kế hoạch (ZCO14 - DMQL)] - CALCULATE(-1 * [Chi phí của đơn vị (ZCO14)], 'FACT - CO PHONG BAN'[OBJECT_NO] = "KSPVCA1Z99")
			)
		lineageTag: e05979fb-e53e-4935-9696-efa3e0bdf60c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ZCO14 Measures (KH NC)' =
			SWITCH(
			    SELECTEDVALUE('PARAMETER - ZCO14 MEASURE GROUP'[STT],""),
			    0,
			        IF(
			            SELECTEDVALUE('DIM - NOI DUNG ZCO14'[Nội dung (ZCO14)]) = "Quỹ tăng thêm"
			            && SELECTEDVALUE('FACT - GL LINE ITEM OFFSET'[GL_ACCOUNT_NO]) = "3561000000",
			            ABS(
			                CALCULATE(
			                    [Số dư đầu kỳ (GL)],
			                    ALL('DIM - NOI DUNG ZCO14'[Nội dung (ZCO14)])
			                )
			            )
			        ),
			    2, CALCULATE([Số phát sinh (ZCO14)],FILTER('DIM - DATE',[Month] = 1)),
			    3, CALCULATE([Số phát sinh (ZCO14)],FILTER('DIM - DATE',[Month] = 2)),
			    4, CALCULATE([Số phát sinh (ZCO14)],FILTER('DIM - DATE',[Month] = 3)),
			    5, CALCULATE([Số phát sinh (ZCO14)],FILTER('DIM - DATE',[Month] = 4)),
			    6, CALCULATE([Số phát sinh (ZCO14)],FILTER('DIM - DATE',[Month] = 5)),
			    7, CALCULATE([Số phát sinh (ZCO14)],FILTER('DIM - DATE',[Month] = 6)),
			    8, CALCULATE([Số phát sinh (ZCO14)],FILTER('DIM - DATE',[Month] = 7)),
			    9, CALCULATE([Số phát sinh (ZCO14)],FILTER('DIM - DATE',[Month] = 8)),
			    10, CALCULATE([Số phát sinh (ZCO14)],FILTER('DIM - DATE',[Month] = 9)),
			    11, CALCULATE([Số phát sinh (ZCO14)],FILTER('DIM - DATE',[Month] = 10)),
			    12, CALCULATE([Số phát sinh (ZCO14)],FILTER('DIM - DATE',[Month] = 11)),
			    13, CALCULATE([Số phát sinh (ZCO14)],FILTER('DIM - DATE',[Month] = 12)),
			    17, CALCULATE([Số phát sinh (ZCO14)], FILTER('FACT - GL LINE ITEM OFFSET', [Nội dung (ZCO14)] ="Đã chi từ quỹ" && [GL_ACCOUNT_NO] = "3561000000")),
			    18,
			        IF(
			            SELECTEDVALUE('DIM - NOI DUNG ZCO14'[Nội dung (ZCO14)]) = "Quỹ tăng thêm"
			            && SELECTEDVALUE('FACT - GL LINE ITEM OFFSET'[GL_ACCOUNT_NO]) = "3561000000",
			            ABS(
			                CALCULATE(
			                    [Số dư cuối kỳ (GL)],
			                    ALL('DIM - NOI DUNG ZCO14'[Nội dung (ZCO14)])
			                )
			            )
			        ),
			    19,
			        DIVIDE(
			            CALCULATE([Số phát sinh (ZCO14)], FILTER('FACT - GL LINE ITEM OFFSET', [Nội dung (ZCO14)] ="Đã chi từ quỹ" && [GL_ACCOUNT_NO] = "3561000000")),
			            ABS(CALCULATE(
			                ([Số dư đầu kỳ (GL)] + [Số dư cuối kỳ (GL)]) / 2,
			                ALL('DIM - NOI DUNG ZCO14'[Nội dung (ZCO14)])
			            ))
			        ) * 100
			)
		lineageTag: c2448540-ef98-49d2-9bfc-1adfce6c9641

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column STT
		dataType: int64
		formatString: 0
		lineageTag: 09e10896-f9ae-4012-afed-9c376ddcc923
		summarizeBy: sum
		isNameInferred
		isDataTypeInferred
		sourceColumn: [STT]

		annotation SummarizationSetBy = Automatic

	column 'Measure group'
		dataType: string
		lineageTag: 14a8fc21-7017-4fdb-938f-4207ef1794a1
		summarizeBy: none
		isNameInferred
		isDataTypeInferred
		sourceColumn: [Measure group]
		sortByColumn: STT

		annotation SummarizationSetBy = Automatic

	partition 'Parameter: ZCO14 Measure group' = calculated
		mode: import
		source =
				DATATABLE(
				    "STT",INTEGER,
				    "Measure group",STRING,
				    {
				        {0, "Số dư đầu kỳ"},
				        {1,"Kế hoạch năm"},
				        {2,"Tháng 1"},
				        {3,"Tháng 2"},
				        {4,"Tháng 3"},
				        {5,"Tháng 4"},
				        {6,"Tháng 5"},
				        {7,"Tháng 6"},
				        {8,"Tháng 7"},
				        {9,"Tháng 8"},
				        {10,"Tháng 9"},
				        {11,"Tháng 10"},
				        {12,"Tháng 11"},
				        {13,"Tháng 12"},
				        {14,"Lũy kế năm"},
				        {15,"% kế hoạch"},
				        {16,"Còn lại"},
				        {17,"Tổng chi"},
				        {18,"Số dư cuối kỳ"},
				        {19, "% đã chi"}
				    }
				 )

	annotation PBI_Id = 7613958171444977a1a3afa41ad1bfdc

