SELECT
    JournalCategoryJeCategoryKey AS JE_CATEGORY_KEY,
    JournalCategoryObjectVerNum AS OBJECT_VERSION_NUMBER,
    JrnlCatTransLangLastUpdatedBy AS LAST_UPDATED_BY,
    JournalCategoryAttribute3 AS ATTRIBUTE3,
    JrnlCatTransLangLastUpdateLogn AS LAST_UPDATE_LOGIN,
    JournalCategoryCreatedBy AS CREATED_BY,
    JrnlCatTransLangLanguage AS LANGUAGE,
    JournalCategoryLastUpdateDate AS LAST_UPDATE_DATE,
    JournalCategoryLastUpdatedBy AS LAST_UPDATED_BY,
    JrnlCatTransLangJeCategoryName AS JE_CATEGORY_NAME,
    JrnlCatTransLangLastUpdateDate AS LAST_UPDATE_DATE,
    JrnlCatTransLangSourceLang AS SOURCE_LANG,
    JournalCategoryLastUpdateLogin AS LAST_UPDATE_LOGIN,
    JrnlCatTransLangUserJeCatName AS USER_JE_CATEGORY_NAME,
    JournalCategoryAttribute5 AS ATTRIBUTE5,
    JournalCategoryAttrCategory AS ATTRIBUTE_CATEGORY,
    JournalCategoryAttribute2 AS ATTRIBUTE2,
    JournalCategoryCreationDate AS CREATION_DATE,
    JournalCategoryAttribute4 AS ATTRIBUTE4,
    JrnlCatTransLangDescription AS DESCRIPTION,
    JrnlCatTransLangCreationDate AS CREATION_DATE,
    JrnlCatTransLangCreatedBy AS CREATED_BY,
    JournalCategoryAttribute1 AS ATTRIBUTE1,
    JournalCategoryJeCategoryName AS JE_CATEGORY_NAME
FROM {{ source('Fusion', 'Journal_Category_PVO') }}