name: 'oracle_analytics'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'oracle_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros", "docs"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]
asset-paths: ["assets"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  catalog: 'uat_catalog'
  fusion_schema: 'brz_fusion'

models:
  +file_format: delta

  elementary:
    +schema: "test"

  oracle_analytics:
    staging:
      +materialized: ephemeral
      +docs:
        node_color: "#cd7f32"
    intermediate:
      +materialized: table
      +docs:
        node_color: "#ffd700"
      procurement:
        +schema: procurement
      finance:
        +schema: finance

        account_payable:
          f_ap_line_item:
            +enabled: false
        fixed_asset:
          +enabled: false

flags:
  require_explicit_package_overrides_for_builtin_materializations: False
  source_freshness_run_project_hooks: True