name: 'oracle_analytics'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'oracle_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros", "docs"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]
asset-paths: ["assets"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  catalog: 'dev_catalog'
  fusion_schema: 'brz_fusion'

models:
  +file_format: delta

  oracle_analytics:
    staging:
      +materialized: ephemeral
      +docs:
        node_color: "#cd7f32"
    intermediate:
      +materialized: table
      +docs:
        node_color: "#ffd700"
      procurement:
        +schema: procurement