SELECT
    TransactionValuationMethod AS VALUATION_METHOD,
    TransactionLegalEntityId AS LEGAL_ENTITY_ID,
    TransactionObjectVersionNumber AS OBJECT_VERSION_NUMBER,
    TransactionSecurityIdInt1 AS SECURITY_ID_INT_1,
    TransactionApplicationId AS APPLICATION_ID,
    TransactionEntityId AS ENTITY_ID,
    TransactionUpgValidFlag AS UPG_VALID_FLAG,
    TransactionSecurityIdInt2 AS SECURITY_ID_INT_2,
    TransactionSourceIdInt2 AS SOURCE_ID_INT_2,
    TransactionSecurityIdInt3 AS SECURITY_ID_INT_3,
    TransactionLedgerId AS LEDGER_ID,
    TransactionLastUpdateDate AS LAST_UPDATE_DATE,
    TransactionTransactionNumber AS TRANSACTION_NUMBER,
    TransactionSourceIdInt3 AS SOURCE_ID_INT_3,
    TransactionSourceIdInt4 AS SOURCE_ID_INT_4,
    TransactionEntityCode AS ENTITY_CODE,
    TransactionSecurityIdChar1 AS SECURITY_ID_CHAR_1,
    TransactionSourceIdChar2 AS SOURCE_ID_CHAR_2,
    TransactionSecurityIdChar2 AS SECURITY_ID_CHAR_2,
    TransactionSourceApplicationId AS SOURCE_APPLICATION_ID,
    TransactionSourceIdChar3 AS SOURCE_ID_CHAR_3,
    TransactionSourceIdChar1 AS SOURCE_ID_CHAR_1,
    TransactionCreatedBy AS CREATED_BY,
    TransactionSourceIdChar4 AS SOURCE_ID_CHAR_4,
    TransactionSourceIdInt1 AS SOURCE_ID_INT_1,
    TransactionLastUpdateLogin AS LAST_UPDATE_LOGIN,
    TransactionSecurityIdChar3 AS SECURITY_ID_CHAR_3,
    TransactionLastUpdatedBy AS LAST_UPDATED_BY,
    TransactionCreationDate AS CREATION_DATE
FROM
    {{ source('Fusion', 'XLA_Transaction_Entity_PVO') }}