SELECT
    EventPEOEventStatusCode AS EVENT_STATUS_CODE,
    EventPEOEventTypeCode AS EVENT_TYPE_CODE,
    EventPEOReferenceNum1 AS REFERENCE_NUM_1,
    EventPEOReferenceNum3 AS REFERENCE_NUM_3,
    EventPEOFileIdentifier AS FILE_IDENTIFIER,
    EventPEOEventNumber AS EVENT_NUMBER,
    EventPEOReferenceChar4 AS REFERENCE_CHAR_4,
    EventPEOReferenceNum4 AS REFERENCE_NUM_4,
    EventPEOEventDate AS EVENT_DATE,
    EventPEOReferenceDate2 AS REFERENCE_DATE_2,
    EventPEOEventId AS EVENT_ID,
    EventPEOReferenceChar1 AS REFERENCE_CHAR_1,
    EventPEOEventPEOBudgetaryControlFlag AS BUDGETARY_CONTROL_FLAG,
    EventPEOReferenceChar3 AS REFERENCE_CHAR_3,
    EventPEOEntityId AS ENTITY_ID,
    EventPEOMergeEventSetId AS MERGE_EVENT_SET_ID,
    EventPEOCreationDate AS CREATION_DATE,
    EventPEOEventPEOCreatedBy AS CREATED_BY,
    EventPEOReferenceDate1 AS REFERENCE_DATE_1,
    EventPEOLastUpdateLogin AS LAST_UPDATE_LOGIN,
    EventPEOLastUpdatedBy AS LAST_UPDATED_BY,
    EventPEOOnHoldFlag AS ON_HOLD_FLAG,
    EventPEOApplicationId AS APPLICATION_ID,
    EventPEOReferenceNum2 AS REFERENCE_NUM_2,
    EventPEOObjectVersionNumber AS OBJECT_VERSION_NUMBER,
    EventPEOProcessStatusCode AS PROCESS_STATUS_CODE,
    EventPEOLastUpdateDate AS LAST_UPDATE_DATE,
    EventPEOReferenceChar2 AS REFERENCE_CHAR_2,
    EventPEOTransactionDate AS TRANSACTION_DATE,
    EventPEOReferenceDate3 AS REFERENCE_DATE_3,
    EventPEOHasWarningsFlag AS HAS_WARNINGS_FLAG,
    EventPEORequestId AS REQUEST_ID,
    EventPEOReferenceDate4 AS REFERENCE_DATE_4
FROM
    {{ source('Fusion', 'XLA_Event_PVO') }}